name: Deploy Zola site from docs/ to GitHub Pages

on:
  push:
    branches:
      - master  # or main, if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # - name: Install Zola
      #   run: |
      #     wget -qO- https://github.com/getzola/zola/releases/latest/download/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz
      #     sudo mv zola /usr/local/bin/
      
      - name Install Zola
        uses: taiki-e/install-action@v2
        with:
            tool: zola@0.19.1
      
      - name: Build site
          run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/public
          publish_branch: gh-pages
